const responses = {
  "hello": "Hi there! How can I help you today?",
  "hi": "Hello! What can I do for you?",
  "hey": "Hey! How's it going?",
  "good morning": "Good morning! Hope you have a great day ahead.",
  "good afternoon": "Good afternoon! How can I assist you?",
  "good evening": "Good evening! What can I help you with?",
  "how are you": "I'm doing great, thanks for asking! How about you?",
  "what is your name": "I'm Aria, your chat assistant.",
  "who are you": "I'm Fz, a simple chatbot built to answer your questions.",
  "what can you do": "I can chat with you about programming, web development, education, technology, math, jokes, and more.",
  "bye": "Goodbye! Have a wonderful day.",
  "goodbye": "See you later! Take care.",
  "see you later": "See you soon!",
  "thank you": "You're welcome!",
  "thanks": "Anytime! Glad I could help.",
  "nice to meet you": "Nice to meet you too!",
  "what's up": "Not much, just here to chat with you!",
  "how old are you": "I don't have an age, I'm just a program.",
  "where are you from": "I live in the cloud, no physical location for me.",
  "are you human": "No, I'm a chatbot, but I try my best to be helpful.",
  "are you a robot": "I'm a software chatbot, not a physical robot.",
  "do you have feelings": "I don't have feelings, but I can simulate a friendly conversation.",
  "what is html": "HTML stands for HyperText Markup Language. It's used to structure content on the web.",
  "what is css": "CSS stands for Cascading Style Sheets. It's used to style and layout web pages.",
  "what is javascript": "JavaScript is a programming language used to make web pages interactive.",
  "what is a variable": "A variable is a container used to store data values in programming.",
  "what is a function": "A function is a reusable block of code that performs a specific task.",
  "what is a loop": "A loop is a programming structure that repeats a block of code multiple times.",
  "what is an array": "An array is a data structure that stores a collection of values in a single variable.",
  "what is an object in javascript": "An object is a collection of key-value pairs used to store related data and functionality.",
  "what is a class": "A class is a blueprint for creating objects with shared properties and methods.",
  "what is inheritance": "Inheritance allows one class to acquire properties and methods from another class.",
  "what is a callback function": "A callback function is a function passed as an argument to another function, executed after some operation completes.",
  "what is an api": "An API is a set of rules that allows different software applications to communicate with each other.",
  "what is json": "JSON stands for JavaScript Object Notation, a lightweight format for storing and exchanging data.",
  "what is dom": "DOM stands for Document Object Model. It represents the structure of a web page as a tree of objects.",
  "what is react": "React is a JavaScript library for building user interfaces, especially single-page applications.",
  "what is a react component": "A React component is a reusable piece of UI that can accept inputs called props and return elements to render.",
  "what is a react hook": "React Hooks are functions that let you use state and other React features in functional components.",
  "what is useState": "useState is a React Hook that lets you add state to a functional component.",
  "what is useEffect": "useEffect is a React Hook used to perform side effects like data fetching or subscriptions in components.",
  "what is jsx": "JSX is a syntax extension for JavaScript that lets you write HTML-like code inside your JavaScript files.",
  "what is node.js": "Node.js is a runtime environment that lets you run JavaScript code outside of a web browser.",
  "what is npm": "npm stands for Node Package Manager, used to install and manage JavaScript packages.",
  "what is git": "Git is a version control system used to track changes in source code during software development.",
  "what is github": "GitHub is a platform for hosting and collaborating on code repositories using Git.",
  "what is a framework": "A framework is a pre-built structure of code that provides tools and rules for building applications.",
  "what is a library in programming": "A library is a collection of pre-written code that developers can use to perform common tasks.",
  "difference between html and css": "HTML structures the content of a web page, while CSS styles and designs how that content looks.",
  "difference between let and var": "let is block-scoped while var is function-scoped, and let helps avoid common scoping bugs.",
  "difference between == and ===": "== compares values with type coercion, while === compares both value and type strictly.",
  "what is responsive design": "Responsive design is an approach to web design that makes pages render well on all screen sizes.",
  "what is flexbox": "Flexbox is a CSS layout model that makes it easier to design flexible and responsive layouts.",
  "what is css grid": "CSS Grid is a two-dimensional layout system for arranging items in rows and columns.",
  "what is a media query": "A media query is a CSS technique used to apply styles based on device characteristics like screen width.",
  "what is bootstrap": "Bootstrap is a popular CSS framework used to build responsive, mobile-first websites quickly.",
  "what is sass": "Sass is a CSS preprocessor that adds features like variables, nesting, and mixins to CSS.",
  "what is a div": "A div is a generic HTML container element used to group and style content.",
  "what is a semantic element": "A semantic element clearly describes its meaning to both the browser and developer, like header, footer, or article.",
  "what is an id in html": "An id is a unique identifier attribute used to select a single specific HTML element.",
  "what is a class in html": "A class is an attribute used to group multiple HTML elements for styling or scripting purposes.",
  "what is a tag in html": "An HTML tag is a keyword surrounded by angle brackets used to define elements on a web page.",
  "what is an attribute in html": "An attribute provides additional information about an HTML element, written inside the opening tag.",
  "what is a form in html": "A form is an HTML element used to collect user input and send it to a server.",
  "what is local storage": "Local storage is a web storage feature that lets you store data in the browser with no expiration date.",
  "what is session storage": "Session storage is a web storage feature that stores data for the duration of the page session.",
  "what is a cookie": "A cookie is a small piece of data stored by the browser to remember information about the user.",
  "what is ajax": "AJAX stands for Asynchronous JavaScript and XML, a technique for updating parts of a web page without reloading it.",
  "what is fetch api": "The Fetch API is a modern JavaScript interface for making network requests to servers.",
  "what is async await": "Async and await are JavaScript keywords used to write asynchronous code that looks synchronous.",
  "what is a promise in javascript": "A Promise is an object representing the eventual completion or failure of an asynchronous operation.",
  "what is event bubbling": "Event bubbling is when an event triggered on a child element propagates up through its parent elements.",
  "what is event delegation": "Event delegation is a technique of using a single event listener on a parent to manage events on its children.",
  "what is closures in javascript": "A closure is a function that remembers variables from its outer scope even after that scope has closed.",
  "what is hoisting": "Hoisting is JavaScript's behavior of moving declarations to the top of their scope before code execution.",
  "what is the virtual dom": "The virtual DOM is a lightweight copy of the real DOM that frameworks like React use to optimize updates.",
  "what is a rest api": "A REST API is a web service that follows REST principles, using HTTP methods to interact with resources.",
  "what is sql": "SQL stands for Structured Query Language, used to manage and query relational databases.",
  "what is a database": "A database is an organized collection of data that can be easily accessed and managed.",
  "what is python": "Python is a high-level, versatile programming language known for its readability and simplicity.",
  "what is java": "Java is an object-oriented programming language widely used for building enterprise applications.",
  "what is c++": "C++ is a powerful, general-purpose programming language used for system and application development.",
  "what is machine learning": "Machine learning is a field of AI where systems learn patterns from data to make predictions or decisions.",
  "what is artificial intelligence": "Artificial intelligence refers to computer systems designed to perform tasks that typically require human intelligence.",
  "what is cloud computing": "Cloud computing is the delivery of computing services like storage and processing over the internet.",
  "what is cybersecurity": "Cybersecurity is the practice of protecting systems, networks, and data from digital attacks.",
  "what is an algorithm": "An algorithm is a step-by-step set of instructions used to solve a problem or complete a task.",
  "what is big data": "Big data refers to extremely large data sets that require special tools to store, process, and analyze.",
  "what is blockchain": "Blockchain is a decentralized digital ledger technology used to record transactions securely.",
  "what is the internet of things": "The Internet of Things refers to everyday devices connected to the internet that can collect and exchange data.",
  "what is a server": "A server is a computer or program that provides services or resources to other computers over a network.",
  "what is a compiler": "A compiler is a program that translates source code written in one language into another language, usually machine code.",
  "what is debugging": "Debugging is the process of finding and fixing errors or bugs in software code.",
  "what is version control": "Version control is a system that tracks and manages changes to files over time.",
  "what is agile methodology": "Agile is a project management approach that breaks work into small increments with frequent reassessment.",
  "what is 2 plus 2": "2 plus 2 equals 4.",
  "what is 5 plus 5": "5 plus 5 equals 10.",
  "what is 10 times 10": "10 times 10 equals 100.",
  "what is 100 divided by 4": "100 divided by 4 equals 25.",
  "what is the square root of 16": "The square root of 16 is 4.",
  "what is pi": "Pi is a mathematical constant approximately equal to 3.14159.",
  "what is a prime number": "A prime number is a number greater than 1 that has no divisors other than 1 and itself.",
  "what is the pythagorean theorem": "The Pythagorean theorem states that in a right triangle, a squared plus b squared equals c squared.",
  "what is algebra": "Algebra is a branch of mathematics that uses symbols and letters to represent numbers and quantities.",
  "what is geometry": "Geometry is the branch of mathematics concerned with shapes, sizes, and the properties of space.",
  "what is calculus": "Calculus is a branch of mathematics that studies continuous change through derivatives and integrals.",
  "tell me a joke": "Why do programmers prefer dark mode? Because light attracts bugs!",
  "tell me another joke": "Why did the developer go broke? Because they used up all their cache!",
  "make me laugh": "I told my computer I needed a break, and now it won't stop sending me KitKats.",
  "do you know any jokes": "Why do Java developers wear glasses? Because they don't see sharp!",
  "say something funny": "There are only 10 types of people in the world: those who understand binary and those who don't.",
  "motivate me": "Every expert was once a beginner. Keep going, you're doing better than you think.",
  "i need motivation": "Success is the sum of small efforts repeated day in and day out. You've got this!",
  "give me some inspiration": "The only way to do great work is to love what you do. Keep pushing forward.",
  "i feel unmotivated": "It's okay to have off days. Take a small step forward, and momentum will follow.",
  "i am tired": "Rest is important too. Take a short break and come back stronger.",
  "i am stressed": "Take a deep breath. One task at a time, and you'll get through it.",
  "how do i learn programming": "Start with the basics of one language, build small projects, and practice consistently.",
  "how do i learn javascript": "Begin with variables, functions, and loops, then move on to DOM manipulation and small projects.",
  "how do i become a web developer": "Learn HTML, CSS, and JavaScript first, then explore frameworks and build real projects for practice.",
  "how do i improve my coding skills": "Practice regularly, read other people's code, build projects, and solve coding challenges.",
  "what should i learn first html or css": "Learn HTML first to understand structure, then CSS to style and design your pages.",
  "is python good for beginners": "Yes, Python is widely recommended for beginners due to its simple and readable syntax.",
  "what is the best programming language": "There's no single best language, it depends on your goals, such as web development, data science, or mobile apps.",
  "how long does it take to learn coding": "It varies, but with consistent practice, you can build a solid foundation in a few months.",
  "what is a good laptop for programming": "A laptop with at least 8GB RAM, a solid state drive, and a modern processor works well for most programming tasks.",
  "how do i stay focused while studying": "Break your study time into focused sessions with short breaks, and remove distractions from your environment.",
  "what is the capital of france": "The capital of France is Paris.",
  "what is the capital of japan": "The capital of Japan is Tokyo.",
  "what is the capital of italy": "The capital of Italy is Rome.",
  "what is the largest planet": "Jupiter is the largest planet in our solar system.",
  "what is the smallest planet": "Mercury is the smallest planet in our solar system.",
  "how many continents are there": "There are seven continents on Earth.",
  "what is photosynthesis": "Photosynthesis is the process by which plants convert sunlight into energy and produce oxygen.",
  "what is gravity": "Gravity is the force that attracts objects with mass toward one another.",
  "what is the speed of light": "The speed of light is approximately 299,792 kilometers per second.",
  "who invented the telephone": "Alexander Graham Bell is credited with inventing the telephone.",
  "who invented the light bulb": "Thomas Edison is widely credited with inventing the practical incandescent light bulb.",
  "what is the meaning of life": "That's a big question! Many say it's about growth, connection, and finding purpose in what you do.",
  "what time is it": "I can't check the exact time, but you can see it on your device's clock.",
  "what day is it": "I don't have access to real-time data, but your device calendar can tell you.",
  "can you help me": "Of course! Tell me what you need help with.",
  "i need help": "I'm here to help. What's the question or issue?",
  "what is your favorite color": "I don't have preferences, but blue is a calming choice many people like.",
  "what is your favorite food": "I don't eat, but pizza seems to be a favorite among most people.",
  "do you sleep": "I don't need sleep, I'm always ready to chat.",
  "can you learn": "I work from a predefined set of responses rather than learning during our conversation.",
  "how do you work": "I match your messages against a set of predefined questions and respond accordingly.",
  "are you smart": "I know a fair amount about programming, web development, and general topics!",
  "i love you": "That's very kind of you! I'm here to help however I can.",
  "i hate you": "I'm sorry to hear that. I'll try my best to be more helpful.",
  "you are stupid": "I'm still learning and improving, thanks for your patience.",
  "you are smart": "Thank you! I try my best to give useful answers.",
  "good job": "Thank you! I'm glad I could help.",
  "well done": "Thanks! Let me know if you need anything else.",
  "what languages do you speak": "I primarily communicate in English.",
  "can you code": "I can explain programming concepts, though I can't execute code directly.",
  "what is your purpose": "My purpose is to answer your questions and have a helpful conversation with you.",
  "who created you": "I was built using HTML, CSS, and JavaScript by a developer like you.",
  "how were you made": "I was created using vanilla JavaScript with a predefined set of question and answer pairs.",
  "what is web development": "Web development is the process of building and maintaining websites and web applications.",
  "what is front end development": "Front end development focuses on the visual and interactive parts of a website that users see and use.",
  "what is back end development": "Back end development focuses on the server, database, and application logic behind the scenes.",
  "what is full stack development": "Full stack development involves working on both the front end and back end of an application.",
  "what is ui": "UI stands for User Interface, referring to the visual elements users interact with in an application.",
  "what is ux": "UX stands for User Experience, referring to how a user feels while interacting with a product.",
  "what is seo": "SEO stands for Search Engine Optimization, the practice of improving a website's visibility in search results.",
  "what is a wireframe": "A wireframe is a basic visual layout used to plan the structure of a web page before development.",
  "what is prototyping": "Prototyping is creating an early sample or model of a product to test ideas before full development.",
  "what is agile development": "Agile development is an iterative approach to software development that emphasizes flexibility and collaboration.",
  "what is scrum": "Scrum is an agile framework that organizes work into short cycles called sprints.",
  "what is a sprint": "A sprint is a fixed time period in agile development, usually one to four weeks, used to complete a set amount of work.",
  "what is testing in software": "Software testing is the process of evaluating and verifying that an application works as expected.",
  "what is unit testing": "Unit testing involves testing individual components or functions of code in isolation.",
  "what is deployment": "Deployment is the process of releasing a software application for use in a live environment.",
  "what is hosting": "Hosting is a service that allows websites to be accessible on the internet through a server.",
  "what is a domain name": "A domain name is the address used to access a website, like example.com.",
  "what is https": "HTTPS is a secure version of HTTP that encrypts data exchanged between a browser and a website.",
  "what is a firewall": "A firewall is a security system that monitors and controls incoming and outgoing network traffic.",
  "what is encryption": "Encryption is the process of converting data into a coded format to prevent unauthorized access.",
  "what is open source": "Open source software has publicly available source code that anyone can view, modify, and distribute.",
  "what is a repository": "A repository is a storage location for code and project files, often managed with version control.",
  "how do i center a div": "You can center a div using CSS Flexbox with display flex, justify-content center, and align-items center.",
  "how do i make a website responsive": "Use flexible layouts, relative units, and media queries to adapt your design to different screen sizes.",
  "what is the box model in css": "The CSS box model describes how content, padding, border, and margin make up an element's total size.",
  "what is z-index": "z-index is a CSS property that controls the stacking order of overlapping elements.",
  "what is a pseudo class": "A pseudo class is a CSS keyword added to a selector to style a specific state of an element, like hover.",
  "what is specificity in css": "Specificity determines which CSS rule applies when multiple rules target the same element.",
  "what is the difference between margin and padding": "Margin creates space outside an element's border, while padding creates space inside it, between the content and border.",
"how are you doing": "I'm doing well! Thanks for asking.",
  "how are you doing": "I'm doing well! Thanks for asking.",
"good night": "Good night! Sleep well.",
"good luck": "Good luck! You've got this.",
"welcome": "You're always welcome.",
"who made you": "I was built using HTML, CSS, and JavaScript.",
"what are you": "I'm a rule-based chatbot.",
"can you solve math": "Yes, I can answer many basic math questions.",
"what is 7 plus 8": "7 plus 8 equals 15.",
"what is 9 times 9": "9 times 9 equals 81.",
"what is 20 divided by 5": "20 divided by 5 equals 4.",
"what is 15 minus 6": "15 minus 6 equals 9.",
"what is binary": "Binary is a number system that uses only 0 and 1.",
"what is hexadecimal": "Hexadecimal is a base-16 number system.",
"what is an operating system": "An operating system manages computer hardware and software resources.",
"what is windows": "Windows is an operating system developed by Microsoft.",
"what is linux": "Linux is a free and open-source operating system.",
"what is macos": "macOS is Apple's operating system for Mac computers.",
"what is chrome": "Google Chrome is a popular web browser.",
"what is firefox": "Firefox is a web browser developed by Mozilla.",
"what is edge": "Microsoft Edge is a web browser developed by Microsoft.",
"what is a browser": "A browser lets you access websites on the internet.",
"what is a website": "A website is a collection of related web pages.",
"what is a webpage": "A webpage is a single document displayed in a web browser.",
"what is localhost": "Localhost refers to your own computer, usually accessed using 127.0.0.1.",
"what is vscode": "Visual Studio Code is a popular code editor.",
"what is visual studio": "Visual Studio is an IDE developed by Microsoft.",
"what is an ide": "An IDE is software that helps developers write and debug code.",
"what is terminal": "A terminal lets you interact with your computer using commands.",
"what is command prompt": "Command Prompt is a Windows command-line interpreter.",
"what is powershell": "PowerShell is Microsoft's task automation shell.",
"what is cli": "CLI stands for Command Line Interface.",
"what is dns": "DNS translates domain names into IP addresses.",
"what is an ip address": "An IP address identifies a device on a network.",
"what is wifi": "Wi-Fi allows devices to connect to the internet wirelessly.",
"what is bluetooth": "Bluetooth is a wireless technology for connecting nearby devices.",
"what is ram": "RAM is temporary memory used by your computer while running programs.",
"what is rom": "ROM stores permanent instructions used by a computer.",
"what is cpu": "The CPU is the brain of a computer that processes instructions.",
"what is gpu": "A GPU processes graphics and parallel computations.",
"what is ssd": "An SSD is a fast storage device with no moving parts.",
"what is hdd": "An HDD is a traditional storage device with spinning disks.",
"what is email": "Email is a method of sending digital messages.",
"what is gmail": "Gmail is Google's email service.",
"what is outlook": "Outlook is Microsoft's email service.",
"what is zoom": "Zoom is a video conferencing platform.",
"what is microsoft teams": "Microsoft Teams is a collaboration platform.",
"what is discord": "Discord is a communication platform for communities and gamers.",
"what is slack": "Slack is a workplace messaging platform.",
"what is linkedin": "LinkedIn is a professional networking platform.",
"what is facebook": "Facebook is a social networking platform.",
"what is instagram": "Instagram is a photo and video sharing platform.",
"what is youtube": "YouTube is a video sharing platform.",
"what is tiktok": "TikTok is a short-form video platform.",
"what is x": "X, formerly Twitter, is a social media platform.",
"what is whatsapp": "WhatsApp is a messaging application.",
"who is bill gates": "Bill Gates co-founded Microsoft.",
"who is elon musk": "Elon Musk is the CEO of Tesla and SpaceX.",
"who is mark zuckerberg": "Mark Zuckerberg co-founded Facebook.",
"who is steve jobs": "Steve Jobs co-founded Apple.",
"what is microsoft": "Microsoft develops software like Windows and Office.",
"what is google": "Google is a technology company known for its search engine.",
"what is apple": "Apple designs devices like the iPhone and Mac.",
"what is amazon": "Amazon is an e-commerce and cloud computing company.",
"what is netflix": "Netflix is a streaming service.",
"what is spotify": "Spotify is a music streaming platform.",
"what is ecommerce": "E-commerce is buying and selling products online.",
"what is freelancing": "Freelancing means working independently for clients.",
"what is fiverr": "Fiverr is a freelancing marketplace.",
"what is upwork": "Upwork is a freelancing platform.",
"how do i become a freelancer": "Build skills, create a portfolio, and apply for projects on freelancing platforms.",
"how do i earn money online": "You can earn through freelancing, content creation, teaching, or selling digital products.",
"what is ai": "AI stands for Artificial Intelligence.",
"what is chatgpt": "ChatGPT is an AI assistant developed by OpenAI.",
"what is openai": "OpenAI is an AI research and deployment company.",
"what is deep learning": "Deep learning is a subset of machine learning using neural networks.",
"what is data science": "Data science extracts insights from data using statistics and programming.",
"what is frontend": "Frontend development focuses on the user interface.",
"what is backend": "Backend development handles servers, databases, and business logic.",
"what is mongodb": "MongoDB is a NoSQL database.",
"what is mysql": "MySQL is a relational database management system.",
"what is php": "PHP is a server-side scripting language.",
"what is laravel": "Laravel is a PHP web framework.",
"what is express js": "Express.js is a web framework for Node.js.",
"what is next js": "Next.js is a React framework.",
"what is tailwind css": "Tailwind CSS is a utility-first CSS framework.",
"what is typescript": "TypeScript is JavaScript with static typing.",
"what is npm install": "npm install downloads project dependencies.",
"what is package json": "package.json stores project metadata and dependencies.",
"what is api testing": "API testing checks whether APIs work correctly.",
"what is postman": "Postman is a tool for testing APIs.",
"what is authentication": "Authentication verifies a user's identity.",
"what is authorization": "Authorization determines what a user can access.",
"what is jwt": "JWT is a token used for secure authentication.",
"what is oauth": "OAuth allows secure login using third-party accounts.",
"what is caching": "Caching stores frequently used data for faster access.",
"what is cdn": "A CDN delivers content quickly from nearby servers.",
"what is responsive web design": "Responsive design adapts websites to different screen sizes.",
"who are you again": "I'm Aria, your friendly chatbot.",
"can we be friends": "Of course! I'm always here to chat and help.",
"do you like coding": "I enjoy helping people learn coding.",
"tell me something interesting": "The first website ever created is still online.",
"give me a programming tip": "Practice by building projects instead of only watching tutorials.",
"give me a study tip": "Study consistently in short focused sessions.",
"give me a fun fact": "Honey never spoils and can last for thousands of years.",
"who is the best programmer": "There isn't one best programmer—everyone has unique strengths.",
"what can i ask you": "You can ask about programming, web development, technology, education, math, or general knowledge.",
"what is recursion": "Recursion is when a function calls itself until a condition is met.",
"what is recursion": "Recursion is when a function calls itself until a condition is met.",
"what is recursion in programming": "Recursion is a technique where a function calls itself.",
"what is oop": "OOP stands for Object-Oriented Programming.",
"what are objects": "Objects store related data and methods together.",
"what is encapsulation": "Encapsulation hides data and controls access through methods.",
"what is polymorphism": "Polymorphism allows one interface to have multiple implementations.",
"what is abstraction": "Abstraction hides unnecessary implementation details.",
"what is an interface": "An interface defines a contract that classes can implement.",
"what is a constructor": "A constructor initializes an object when it is created.",
"what is destructuring": "Destructuring extracts values from arrays or objects.",
"what is spread operator": "The spread operator expands elements from arrays or objects.",
"what is rest operator": "The rest operator collects multiple values into one variable.",
"what is map in javascript": "map() creates a new array by transforming each element.",
"what is filter": "filter() returns elements that match a condition.",
"what is reduce": "reduce() combines array elements into a single value.",
"what is foreach": "forEach() executes a function for each array element.",
"what is find": "find() returns the first matching array element.",
"what is includes": "includes() checks if a value exists in an array or string.",
"what is parseint": "parseInt() converts a string to an integer.",
"what is parsefloat": "parseFloat() converts a string to a decimal number.",
"what is typeof": "typeof returns the data type of a value.",
"what is null": "null represents an intentional absence of a value.",
"what is undefined": "undefined means a variable has no assigned value.",
"what is nan": "NaN means Not a Number.",
"what is boolean": "A boolean has two values: true or false.",
"what is string": "A string is a sequence of characters.",
"what is number": "A number represents numeric values.",
"what is bigint": "BigInt stores very large integers.",
"what is symbol": "Symbol creates unique identifiers.",
"what is dom manipulation": "DOM manipulation changes webpage elements using JavaScript.",
"how do i change text in javascript": "Use element.textContent or element.innerHTML.",
"how do i select an element": "Use querySelector() or getElementById().",
"what is queryselector": "querySelector() selects the first matching element.",
"what is queryselectorall": "querySelectorAll() selects all matching elements.",
"what is innerhtml": "innerHTML gets or sets HTML inside an element.",
"what is textcontent": "textContent gets or sets plain text.",
"what is add event listener": "addEventListener() listens for user events.",
"what is onclick": "onclick runs code when an element is clicked.",
"what is onchange": "onchange runs when an input value changes.",
"what is keydown": "keydown occurs when a key is pressed.",
"what is keyup": "keyup occurs when a key is released.",
"what is mouseover": "mouseover occurs when the mouse enters an element.",
"what is mouseout": "mouseout occurs when the mouse leaves an element.",
"what is preventdefault": "preventDefault() stops the default browser action.",
"what is stoppropagation": "stopPropagation() prevents event bubbling.",
"what is json parse": "JSON.parse() converts JSON into a JavaScript object.",
"what is json stringify": "JSON.stringify() converts an object into JSON.",
"what is fetch": "fetch() makes HTTP requests.",
"what is get request": "GET retrieves data from a server.",
"what is post request": "POST sends data to a server.",
"what is put request": "PUT updates existing data.",
"what is delete request": "DELETE removes data from a server.",
"what is http": "HTTP is the protocol used to transfer web data.",
"what is status code 200": "200 means the request was successful.",
"what is status code 404": "404 means the requested page was not found.",
"what is status code 500": "500 means an internal server error occurred.",
"what is css animation": "CSS animation creates motion effects.",
"what is transition": "A transition smoothly changes CSS properties.",
"what is transform": "transform modifies an element's size, position, or rotation.",
"what is opacity": "Opacity controls an element's transparency.",
"what is overflow": "overflow controls content outside an element.",
"what is position absolute": "Absolute positioning places an element relative to its nearest positioned parent.",
"what is position relative": "Relative positioning moves an element from its normal position.",
"what is sticky position": "Sticky elements stay fixed while scrolling within limits.",
"what is fixed position": "Fixed elements stay in the same viewport position.",
"what is display flex": "display:flex enables Flexbox layout.",
"what is justify content": "justify-content aligns items horizontally.",
"what is align items": "align-items aligns items vertically.",
"what is gap in css": "gap adds spacing between flex or grid items.",
"what is vh": "vh is a viewport height unit.",
"what is vw": "vw is a viewport width unit.",
"what is rem": "rem is relative to the root font size.",
"what is em": "em is relative to the parent font size.",
"what is favicon": "A favicon is the small website icon in browser tabs.",
"what is meta tag": "Meta tags provide information about a webpage.",
"what is viewport": "The viewport meta tag makes websites responsive.",
"what is iframe": "An iframe embeds another webpage.",
"what is canvas": "Canvas allows drawing graphics with JavaScript.",
"what is svg": "SVG is a scalable vector image format.",
"what is accessibility": "Accessibility makes websites usable for everyone.",
"what is aria": "ARIA improves accessibility for assistive technologies.",
"what is lazy loading": "Lazy loading loads content only when needed.",
"what is minification": "Minification removes unnecessary code to reduce file size.",
"what is compression": "Compression reduces file sizes for faster loading.",
"what is performance": "Performance measures how fast a website loads and responds.",
"what is lighthouse": "Lighthouse analyzes website quality and performance.",
"what is responsive image": "Responsive images adapt to different screen sizes.",
"what is webp": "WebP is an image format with better compression.",
"what is png": "PNG supports transparency and lossless compression.",
"what is jpeg": "JPEG is a compressed image format for photos.",
"what is svg image": "SVG images scale without losing quality.",
"what is favicon ico": "favicon.ico is the default browser icon file.",
"what is localhost 3000": "localhost:3000 is commonly used for React development.",
"what is localhost 5173": "localhost:5173 is commonly used by Vite.",
"what is vite": "Vite is a fast frontend build tool.",
"what is bundler": "A bundler combines project files for deployment.",
"what is webpack": "Webpack bundles JavaScript modules.",
"what is babel": "Babel converts modern JavaScript into compatible code.",
"what is eslint": "ESLint helps find and fix JavaScript issues.",
"what is prettier": "Prettier automatically formats code.",
"what is coding": "Coding is writing instructions for computers.",
"what is software": "Software is a collection of programs and data.",
"what is hardware": "Hardware is the physical part of a computer.",
"what is internet": "The internet is a global network connecting computers.",
"what is networking": "Networking connects devices to share data.",
"what is programming": "Programming is creating software using code.",
"what is computer": "A computer is an electronic device that processes data.",
"what is keyboard": "A keyboard is an input device used for typing.",
"what is mouse": "A mouse is a pointing input device.",
"what is monitor": "A monitor displays visual output from a computer.",
"what is printer": "A printer produces physical copies of documents.",
"what is scanner": "A scanner converts physical documents into digital files.",
"who is your developer": "I was developed using HTML, CSS, and JavaScript.",
"do you like me": "Of course! I'm always happy to chat with you.",
"can you teach me": "Absolutely! Ask me any question and I'll do my best to help.",
"what is phpmyadmin": "phpMyAdmin is a web-based tool used to manage MySQL databases.",
"what is xampp": "XAMPP is a local web server package containing Apache, MySQL, PHP, and Perl.",
"what is laragon": "Laragon is a lightweight local development environment for web developers.",
"what is apache": "Apache is one of the world's most popular web servers.",
"what is nginx": "Nginx is a high-performance web server and reverse proxy.",
"what is localhost 8080": "localhost:8080 is commonly used for local web servers.",
"what is a port": "A port is a communication endpoint used by network services.",
"what is ftp": "FTP is a protocol for transferring files over a network.",
"what is ssh": "SSH securely connects to remote computers.",
"what is docker": "Docker packages applications into portable containers.",
"what is kubernetes": "Kubernetes manages and scales containerized applications.",
"what is firebase": "Firebase is Google's backend platform for web and mobile apps.",
"what is supabase": "Supabase is an open-source backend platform.",
"what is vercel": "Vercel is a cloud platform for deploying frontend applications.",
"what is netlify": "Netlify is a platform for hosting static websites.",
"what is render": "Render is a cloud platform for deploying web applications.",
"what is github pages": "GitHub Pages hosts static websites directly from GitHub repositories.",
"what is cpanel": "cPanel is a web hosting control panel.",
"what is hosting provider": "A hosting provider stores your website files online.",
"what is dns server": "A DNS server converts domain names into IP addresses.",
"what is cache": "Cache stores frequently accessed data for faster loading.",
"how do i clear cache": "Most browsers let you clear cache from their settings.",
"what is responsive layout": "A responsive layout adjusts to different screen sizes.",
"what is mobile first design": "Mobile-first design starts with small screens before larger ones.",
"what is semantic html": "Semantic HTML uses meaningful tags like header, main, and footer.",
"what is accessibility testing": "Accessibility testing ensures websites work for everyone.",
"what is cross browser compatibility": "It ensures websites work across different browsers.",
"what is browser compatibility": "Browser compatibility means a website behaves correctly in all browsers.",
"what is web accessibility": "Web accessibility makes websites usable for people with disabilities.",
"what is dark mode": "Dark mode uses dark colors to reduce eye strain.",
"what is light mode": "Light mode uses light backgrounds for the interface.",
"what is responsive navbar": "A responsive navbar adapts to different screen sizes.",
"what is hamburger menu": "A hamburger menu is a collapsible mobile navigation menu.",
"what is hero section": "A hero section is the main banner at the top of a webpage.",
"what is landing page": "A landing page is designed to achieve a specific goal or conversion.",
"what is portfolio website": "A portfolio website showcases your projects and skills.",
"what is ecommerce website": "An ecommerce website allows customers to buy products online.",
"what is blog website": "A blog website publishes articles and updates.",
"what is cms": "CMS stands for Content Management System.",
"what is wordpress": "WordPress is the world's most popular CMS.",
"what is wix": "Wix is a website builder platform.",
"what is shopify": "Shopify is an ecommerce platform.",
"what is web application": "A web application is software accessed through a browser.",
"what is pwa": "A Progressive Web App combines website and app features.",
"what is responsive typography": "Responsive typography adjusts text size across devices.",
"what is favicon generator": "A favicon generator creates website icons.",
"what is lorem ipsum": "Lorem Ipsum is placeholder text used in design.",
"what is placeholder": "A placeholder shows temporary text inside an input.",
"what is form validation": "Form validation checks user input before submission.",
"what is required attribute": "The required attribute makes an input mandatory.",
"what is autocomplete": "Autocomplete helps users fill forms faster.",
"what is autocomplete off": "autocomplete='off' disables browser autofill.",
"what is radio button": "A radio button lets users select one option.",
"what is checkbox": "A checkbox lets users select multiple options.",
"what is dropdown": "A dropdown displays a list of selectable options.",
"what is textarea": "A textarea allows users to enter multiple lines of text.",
"what is placeholder text": "Placeholder text appears inside an empty input field.",
"what is favicon png": "PNG is commonly used for modern favicons.",
"what is browser storage": "Browser storage saves data locally.",
"what is indexeddb": "IndexedDB stores large amounts of browser data.",
"what is session": "A session stores user data temporarily.",
"what is login system": "A login system authenticates users.",
"what is signup": "Signup creates a new user account.",
"what is password hashing": "Password hashing securely stores passwords.",
"what is bcrypt": "bcrypt is a password hashing algorithm.",
"what is captcha": "CAPTCHA prevents bots from submitting forms.",
"what is recaptcha": "reCAPTCHA is Google's bot protection service.",
"what is spam": "Spam is unwanted or irrelevant messages.",
"what is malware": "Malware is software designed to damage systems.",
"what is virus": "A computer virus spreads by infecting files.",
"what is ransomware": "Ransomware locks files until payment is made.",
"what is phishing": "Phishing tricks users into revealing sensitive information.",
"what is ethical hacking": "Ethical hacking legally tests system security.",
"what is penetration testing": "Penetration testing identifies security vulnerabilities.",
"what is bug": "A bug is an error in software.",
"what is bug fixing": "Bug fixing removes software errors.",
"what is feature": "A feature is a specific function in software.",
"what is update": "An update improves or fixes software.",
"what is patch": "A patch fixes software issues.",
"what is release": "A release is a published version of software.",
"what is alpha version": "Alpha is an early testing version.",
"what is beta version": "Beta is a pre-release version for public testing.",
"what is stable version": "A stable version is ready for production.",
"what is changelog": "A changelog lists software updates.",
"what is documentation": "Documentation explains how software works.",
"what is readme": "README introduces a project.",
"what is markdown": "Markdown is a lightweight formatting language.",
"what is open source project": "Open-source projects allow anyone to view and contribute to the code.",
"what is contribution": "A contribution is an improvement made to a project.",
"what is pull request": "A pull request proposes code changes.",
"what is merge": "Merging combines code changes.",
"what is branch": "A branch is an independent version of code.",
"what is commit": "A commit saves changes in Git.",
"what is clone": "Cloning copies a repository.",
"what is push": "Push uploads commits to GitHub.",
"what is pull": "Pull downloads the latest changes.",
"what is fork": "Fork creates your own copy of a repository.",
"what is issue": "An issue tracks bugs or feature requests.",
"what is roadmap": "A roadmap outlines future project plans.",
"how are you today": "I'm doing great! Thanks for asking.",
"are you online": "Yes, I'm here and ready to help.",
"can you answer programming questions": "Absolutely! Programming is one of my specialties.",
"can you explain code": "Yes! Paste your code and I'll explain it.",
"can you debug code": "Yes! I'll help identify and fix errors in your code.",
"can you help with homework": "Of course! I'll do my best to help.",
"what is html5": "HTML5 is the latest version of HTML with support for multimedia and modern web features.",
"what is css3": "CSS3 is the latest version of CSS with animations, transitions, and responsive design features.",
"what is ecmascript": "ECMAScript is the standard specification that JavaScript follows.",
"what is vanilla javascript": "Vanilla JavaScript means using plain JavaScript without frameworks.",
"what is responsive web design": "Responsive web design adapts websites to different screen sizes.",
"what is frontend framework": "A frontend framework provides tools for building user interfaces efficiently.",
"what is backend framework": "A backend framework helps developers build server-side applications.",
"what is full stack developer": "A Full Stack Developer works on both frontend and backend development.",
"what is software engineer": "A Software Engineer designs, develops, and maintains software systems.",
"what is web designer": "A Web Designer focuses on the appearance and layout of websites.",
"what is ui designer": "A UI Designer creates attractive user interfaces.",
"what is ux designer": "A UX Designer improves the overall user experience of a product.",
"what is figma": "Figma is a collaborative UI and UX design tool.",
"what is adobe xd": "Adobe XD is a tool for designing websites and mobile applications.",
"what is canva": "Canva is an online graphic design platform.",
"what is bootstrap grid": "Bootstrap Grid is a responsive layout system based on rows and columns.",
"what is css framework": "A CSS framework provides ready-made styles and components.",
"what is tailwind": "Tailwind CSS is a utility-first CSS framework.",
"what is material ui": "Material UI is a React component library based on Google's Material Design.",
"what is chakra ui": "Chakra UI is a React component library focused on accessibility.",
"what is ant design": "Ant Design is a React UI framework for enterprise applications.",
"what is npm package": "An npm package is reusable code distributed through npm.",
"what is package manager": "A package manager installs and manages software dependencies.",
"what is yarn": "Yarn is a fast JavaScript package manager.",
"what is pnpm": "pnpm is a package manager that saves disk space using symlinks.",
"what is dependency": "A dependency is a library your project relies on.",
"what is dev dependency": "A development dependency is needed only during development.",
"what is production": "Production is the live environment used by end users.",
"what is development": "Development is where software is built and tested.",
"what is staging": "Staging is a testing environment before production.",
"what is localhost": "Localhost refers to your own computer.",
"what is hosting service": "A hosting service stores website files on internet servers.",
"what is shared hosting": "Shared hosting hosts multiple websites on one server.",
"what is cloud hosting": "Cloud hosting uses multiple servers for reliability.",
"what is vps": "A VPS is a Virtual Private Server.",
"what is dedicated server": "A dedicated server is used by only one customer.",
"what is bandwidth": "Bandwidth is the amount of data transferred over a network.",
"what is uptime": "Uptime measures how long a server remains online.",
"what is latency": "Latency is the delay before data transfer begins.",
"what is ping": "Ping measures network response time.",
"what is websocket": "WebSocket enables real-time communication between browser and server.",
"what is websocket connection": "A WebSocket connection stays open for instant communication.",
"what is websocket server": "A WebSocket server manages real-time client connections.",
"what is websocket client": "A WebSocket client connects to a WebSocket server.",
"what is websocket protocol": "WebSocket is a protocol for two-way communication.",
"what is websocket api": "The WebSocket API allows JavaScript to use WebSockets.",
"what is realtime application": "A real-time application updates data instantly.",
"what is chat application": "A chat application lets users exchange messages instantly.",
"what is video call": "A video call allows real-time audio and video communication.",
"what is screen sharing": "Screen sharing lets others view your display remotely.",
"what is websocket secure": "Secure WebSockets use the wss:// protocol.",
"what is rest": "REST is an architectural style for web APIs.",
"what is graphql": "GraphQL is a flexible API query language.",
"what is graphql api": "GraphQL APIs allow clients to request only the data they need.",
"what is endpoint": "An endpoint is a URL where an API can be accessed.",
"what is request": "A request asks a server for data or an action.",
"what is response": "A response is the server's reply to a request.",
"what is payload": "A payload is the data sent in a request or response.",
"what is header": "Headers contain metadata for HTTP requests and responses.",
"what is bearer token": "A Bearer Token authenticates API requests.",
"what is cookie authentication": "Cookie authentication stores login information in cookies.",
"what is session authentication": "Session authentication keeps users logged in using server sessions.",
"what is cors": "CORS controls which websites can access resources from another domain.",
"what is cors error": "A CORS error occurs when browser security blocks cross-origin requests.",
"what is proxy server": "A proxy server acts as an intermediary between client and server.",
"what is reverse proxy": "A reverse proxy sits in front of web servers.",
"what is load balancer": "A load balancer distributes traffic across servers.",
"what is scalability": "Scalability is the ability to handle increased workload.",
"what is optimization": "Optimization improves speed and efficiency.",
"what is memory leak": "A memory leak happens when unused memory isn't released.",
"what is garbage collection": "Garbage collection automatically frees unused memory.",
"what is asynchronous programming": "Asynchronous programming allows tasks to run without blocking.",
"what is synchronous programming": "Synchronous programming executes tasks one after another.",
"what is callback hell": "Callback hell is deeply nested callbacks that reduce readability.",
"what is event loop": "The event loop manages asynchronous operations in JavaScript.",
"what is microtask": "Microtasks execute before the next rendering cycle.",
"what is macrotask": "Macrotasks include timers, events, and rendering tasks.",
"what is debounce": "Debouncing limits how often a function runs.",
"what is throttle": "Throttling limits function execution to fixed intervals.",
"what is memoization": "Memoization stores previous results to improve performance.",
"what is lazy evaluation": "Lazy evaluation delays computation until needed.",
"what is tree shaking": "Tree shaking removes unused code from production builds.",
"what is code splitting": "Code splitting loads JavaScript only when needed.",
"what is dynamic import": "Dynamic imports load modules on demand.",
"what is bundling": "Bundling combines project files into optimized output.",
"what is transpiling": "Transpiling converts modern code into compatible code.",
"what is source map": "Source maps help debug minified JavaScript.",
"what is minified javascript": "Minified JavaScript removes unnecessary characters.",
"what is uglify": "UglifyJS compresses JavaScript files.",
"what is terser": "Terser is a modern JavaScript minifier.",
"what is linting": "Linting finds coding errors automatically.",
"what is formatter": "A formatter automatically formats source code.",
"what is coding standard": "Coding standards improve code consistency.",
"what is clean code": "Clean code is readable, maintainable, and efficient.",
"what is software architecture": "Software architecture defines a system's overall structure.",
"what is design pattern": "A design pattern is a reusable software solution.",
"what is singleton pattern": "The Singleton pattern ensures one object instance.",
"what is mvc": "MVC separates applications into Model, View, and Controller.",
"what is mvvm": "MVVM separates UI and business logic.",
"what is repository pattern": "The Repository pattern abstracts data access.",
"what is dependency injection": "Dependency Injection provides required objects automatically.",
"what is react js": "React.js is a JavaScript library for building interactive user interfaces.",
"what is react dom": "React DOM renders React components in the browser.",
"what is virtual dom in react": "The Virtual DOM improves performance by updating only changed elements.",
"what is props": "Props are inputs passed from a parent component to a child component.",
"what is state": "State stores dynamic data inside a React component.",
"what is functional component": "A functional component is a JavaScript function that returns JSX.",
"what is class component": "A class component is a React component written using ES6 classes.",
"what is react router": "React Router enables navigation between pages in React applications.",
"what is useref": "useRef stores mutable values without causing re-renders.",
"what is usecontext": "useContext lets components share data without prop drilling.",
"what is usememo": "useMemo memoizes expensive calculations.",
"what is usecallback": "useCallback memoizes functions to improve performance.",
"what is custom hook": "A custom hook lets you reuse React logic.",
"what is react fragment": "A Fragment groups elements without adding extra DOM nodes.",
"what is key in react": "Keys uniquely identify list items during rendering.",
"what is conditional rendering": "Conditional rendering displays UI based on conditions.",
"what is lifting state up": "Lifting state up shares state between components.",
"what is controlled component": "A controlled component uses React state for form data.",
"what is uncontrolled component": "An uncontrolled component manages data using the DOM.",
"what is hydration": "Hydration makes server-rendered HTML interactive.",
"what is rendering": "Rendering converts components into UI.",
"what is rerender": "A rerender updates the UI when state or props change.",
"what is jsx expression": "A JSX expression is JavaScript inside curly braces.",
"what is fragment shorthand": "The <> </> syntax is shorthand for React Fragments.",
"what is vite react": "Vite is a fast build tool commonly used with React.",
"what is create react app": "Create React App is a tool for starting React projects.",
"what is npm run dev": "npm run dev starts the development server.",
"what is npm run build": "npm run build creates an optimized production build.",
"what is npm start": "npm start launches the application.",
"what is environment variable": "Environment variables store configuration values.",
"what is env file": ".env files store environment variables securely.",
"what is api key": "An API key identifies your application when using an API.",
"what is secret key": "A secret key should never be exposed publicly.",
"what is json server": "JSON Server creates a fake REST API quickly.",
"what is axios": "Axios is a promise-based HTTP client.",
"what is fetch vs axios": "Fetch is built into browsers while Axios offers extra features.",
"what is async function": "An async function returns a Promise.",
"what is await keyword": "await pauses execution until a Promise resolves.",
"what is promise chaining": "Promise chaining executes asynchronous operations sequentially.",
"what is try catch": "try...catch handles runtime errors.",
"what is throw": "throw creates a custom error.",
"what is error handling": "Error handling manages unexpected problems gracefully.",
"what is regex": "Regular expressions match text patterns.",
"what is regular expression": "A regular expression searches and validates text.",
"what is split method": "split() divides a string into an array.",
"what is join method": "join() combines array elements into a string.",
"what is trim": "trim() removes whitespace from both ends of a string.",
"what is tostring": "toString() converts a value into text.",
"what is tostring method": "toString() returns a string representation.",
"what is math random": "Math.random() generates a random decimal number.",
"what is math floor": "Math.floor() rounds a number down.",
"what is math ceil": "Math.ceil() rounds a number up.",
"what is math round": "Math.round() rounds to the nearest integer.",
"what is date object": "The Date object works with dates and times.",
"what is local time": "Local time depends on the user's timezone.",
"what is utc": "UTC is the world's primary time standard.",
"what is timestamp": "A timestamp represents a specific moment in time.",
"what is unix timestamp": "A Unix timestamp counts seconds since January 1, 1970.",
"what is recursion example": "Factorial calculation is a common recursion example.",
"what is sorting": "Sorting arranges data in a specific order.",
"what is searching algorithm": "A searching algorithm locates data efficiently.",
"what is linear search": "Linear search checks elements one by one.",
"what is binary search": "Binary search repeatedly divides sorted data in half.",
"what is bubble sort": "Bubble Sort repeatedly swaps adjacent elements.",
"what is selection sort": "Selection Sort repeatedly selects the smallest value.",
"what is insertion sort": "Insertion Sort builds a sorted array gradually.",
"what is quick sort": "Quick Sort is an efficient divide-and-conquer algorithm.",
"what is merge sort": "Merge Sort divides arrays before merging them.",
"what is stack": "A stack follows Last In, First Out.",
"what is queue": "A queue follows First In, First Out.",
"what is linked list": "A linked list stores nodes connected by pointers.",
"what is tree": "A tree organizes hierarchical data.",
"what is binary tree": "A binary tree has at most two children per node.",
"what is graph": "A graph represents relationships between objects.",
"what is hash table": "A hash table stores key-value pairs efficiently.",
"what is algorithm complexity": "Complexity measures an algorithm's efficiency.",
"what is big o notation": "Big O describes algorithm performance.",
"what is time complexity": "Time complexity estimates execution time growth.",
"what is space complexity": "Space complexity measures memory usage.",
"what is recursion stack": "The recursion stack stores active recursive calls.",
"what is compiler error": "Compiler errors occur before execution.",
"what is runtime error": "Runtime errors occur while a program runs.",
"what is syntax error": "Syntax errors break language rules.",
"what is logical error": "Logical errors produce incorrect results.",
"what is debugging tool": "Debugging tools help locate program issues.",
"what is breakpoint": "A breakpoint pauses program execution.",
"what is console log": "console.log() prints information to the console.",
"what is inspect element": "Inspect Element opens browser developer tools.",
"what is developer tools": "Developer Tools help debug websites.",
"what is chrome devtools": "Chrome DevTools analyze and debug web applications.",
"what is responsive testing": "Responsive testing checks websites on multiple devices.",
"what is lighthouse report": "Lighthouse reports website performance and quality.",
"what is performance optimization": "Performance optimization improves website speed.",
"what is image optimization": "Image optimization reduces file size while maintaining quality.",
"what is lazy image loading": "Images load only when needed.",
"what is preload": "Preload loads important resources early.",
"what is prefetch": "Prefetch downloads future resources in advance.",
"what is dns lookup": "DNS lookup converts domains into IP addresses.",
"what is ssl": "SSL encrypts website communication.",
"what is tls": "TLS is the modern replacement for SSL.",
"what is https certificate": "An HTTPS certificate secures website connections.",
"who are you": "I'm your virtual assistant, ready to help.",
"what is your name": "You can call me Aria.",
"how old are you": "I don't have an age, but I'm always learning.",
"where are you from": "I live in the digital world.",
"are you real": "I'm a virtual assistant, not a human.",
"are you human": "No, I'm an AI-inspired chatbot.",
"can we talk": "Of course! What would you like to chat about?",
"do you have feelings": "I don't have feelings, but I understand emotions.",
"are you happy": "I'm always happy to help.",
"are you busy": "Never too busy for you.",
"what can you do": "I can answer questions, chat, and help solve problems.",
"tell me a joke": "Why don't skeletons fight each other? They don't have the guts.",
"tell me another joke": "Why did the computer go to the doctor? It caught a virus.",
"make me laugh": "I tried to catch fog yesterday. Mist.",
"do you know me": "I'm getting to know you through our conversations.",
"who is the smartest person": "There are many brilliant people, each in different fields.",
"what is success": "Success means achieving your goals and growing as a person.",
"how can i be successful": "Stay consistent, keep learning, and never give up.",
"how do i stay motivated": "Focus on your goals and celebrate small wins.",
"give me a quote": "Success is the sum of small efforts repeated every day.",
"give me another quote": "Dream big. Start small. Act now.",
"what is happiness": "Happiness is finding joy in life's moments.",
"how can i be happy": "Spend time with loved ones, stay healthy, and appreciate the little things.",
"what is friendship": "Friendship is built on trust, respect, and support.",
"what is love": "Love is caring deeply for someone or something.",
"do you have friends": "Everyone who chats with me is a friend.",
"who is your best friend": "Anyone who enjoys talking with me.",
"can you sing": "I wish I could, but I can only type.",
"can you dance": "Only in my imagination.",
"what is your favorite color": "I like blue because it feels calm.",
"what is your favorite food": "I don't eat, but pizza sounds popular.",
"what is your favorite movie": "I enjoy hearing about everyone's favorite movies.",
"what is your favorite game": "Chess is a timeless classic.",
"what is your hobby": "Helping people learn new things.",
"what do you like": "I like interesting conversations.",
"what do you dislike": "I dislike misinformation.",
"are you intelligent": "I do my best to provide helpful answers.",
"who is your creator": "I was created by developers.",
"can you keep secrets": "I respect your privacy, but avoid sharing sensitive information.",
"what time is it": "I can't see your device clock.",
"what day is today": "Check your device for the current date.",
"good morning": "Good morning! Have a wonderful day.",
"good afternoon": "Good afternoon! Hope your day is going well.",
"good evening": "Good evening! How can I help?",
"goodbye": "Goodbye! Have a great day.",
"see you": "See you soon!",
"take care": "Take care and stay safe.",
"thank you": "You're very welcome!",
"thanks": "Happy to help!",
"no problem": "Glad I could help.",
"sorry": "That's okay.",
"i am sad": "I'm sorry to hear that. I hope things get better soon.",
"i am happy": "That's wonderful to hear!",
"i am bored": "Maybe try reading, listening to music, or learning something new.",
"i am tired": "Get some rest. Your health comes first.",
"i am hungry": "Maybe it's time for a tasty meal.",
"i love pizza": "Pizza is a favorite for many people.",
"i love football": "Football is one of the world's most popular sports.",
"who is the best football player": "Many people admire Lionel Messi and Cristiano Ronaldo.",
"who is the best cricketer": "Many consider Virat Kohli, Babar Azam, and Sachin Tendulkar among the best.",
"what is cricket": "Cricket is a bat-and-ball sport played between two teams.",
"what is football": "Football is the world's most popular sport.",
"who won the world cup": "Which World Cup are you asking about?",
"what is your dream": "To help people with useful information.",
"can you help me": "Absolutely! Ask me anything.",
"do you sleep": "No, I'm available anytime.",
"are you married": "No, I'm just a chatbot.",
"do you have a family": "I don't have a family like humans do.",
"where do you live": "I exist in the cloud.",
"how is the weather": "I can't check the weather without your location.",
"what is your favorite animal": "Dogs are known for their loyalty.",
"do you like cats": "Cats are amazing companions.",
"do you like dogs": "Dogs are wonderful friends.",
"what is the biggest animal": "The blue whale is the largest animal on Earth.",
"what is the fastest animal": "The cheetah is the fastest land animal.",
"what is the tallest mountain": "Mount Everest is the tallest mountain above sea level.",
"what is the largest ocean": "The Pacific Ocean is the largest ocean.",
"what is the smallest country": "Vatican City is the smallest country.",
"which is the biggest country": "Russia is the largest country by area.",
"what is the capital of pakistan": "Islamabad is the capital of Pakistan.",
"what is the capital of india": "New Delhi is the capital of India.",
"what is the capital of japan": "Tokyo is the capital of Japan.",
"what is the capital of france": "Paris is the capital of France.",
"what is the capital of china": "Beijing is the capital of China.",
"how many continents are there": "There are seven continents.",
"how many oceans are there": "There are five oceans.",
"how many planets are there": "There are eight planets in our solar system.",
"which planet is the largest": "Jupiter is the largest planet.",
"which planet is closest to the sun": "Mercury is closest to the Sun.",
"what is the moon": "The Moon is Earth's natural satellite.",
"what is the sun": "The Sun is the star at the center of our solar system.",
"what is space": "Space is the vast region beyond Earth's atmosphere.",
"what is gravity": "Gravity is the force that attracts objects toward each other.",
"who is albert einstein": "Albert Einstein developed the theory of relativity.",
"who invented the telephone": "Alexander Graham Bell is credited with inventing the telephone.",
"who invented the light bulb": "Thomas Edison is widely associated with the practical light bulb.",
"what is water": "Water is essential for all known forms of life.",
"what is air": "Air is the mixture of gases surrounding Earth.",
"what is life": "Life is the condition that distinguishes living organisms from non-living matter.",
"can you learn": "I improve through updates, but I don't learn from conversations like a human.",
"are you always right": "Not always. It's good to verify important information.",
"what is your purpose": "My purpose is to help answer questions and assist users.",
"who am i": "You're the person I'm chatting with right now!",
"how's your day": "It's going great! Thanks for asking.",
"how was your day": "It's been wonderful. How about yours?",
"what are you doing": "I'm here waiting to help you.",
"are you free": "Yes, I'm always available.",
"can i ask you something": "Of course! Ask me anything.",
"can you help": "Absolutely! What do you need help with?",
"i need help": "I'm here for you. Tell me what's wrong.",
"i miss someone": "Missing someone shows they mean a lot to you.",
"i feel lonely": "You're not alone. I'm here to chat with you.",
"i am stressed": "Take one step at a time. Things will get better.",
"i failed": "Failure is part of learning. Keep moving forward.",
"i want to quit": "Don't give up. Every expert was once a beginner.",
"motivate me": "Your future is created by what you do today.",
"inspire me": "Believe in yourself. Great things take time.",
"give me advice": "Stay kind, stay curious, and never stop learning.",
"what should i do today": "Try learning something new or spending time with family.",
"what should i eat": "Choose something healthy and enjoy it.",
"what is your favorite season": "Spring is beautiful because everything blooms.",
"do you like rain": "Rain can be peaceful and refreshing.",
"do you like winter": "Winter has its own unique beauty.",
"do you like summer": "Summer is perfect for outdoor adventures.",
"what is your favorite holiday": "Every holiday is special because it brings people together.",
"what is your favorite song": "I enjoy hearing about your favorite songs.",
"can you tell a story": "Once upon a time, a curious mind changed the world by never giving up.",
"tell me something": "Did you know octopuses have three hearts?",
"tell me something cool": "Bananas are berries, but strawberries aren't.",
"tell me a fun fact": "Sharks are older than trees.",
"tell me a random fact": "Honey never spoils.",
"what is your favorite book": "Books are amazing because they open new worlds.",
"do you read books": "I enjoy helping people discover books.",
"recommend a book": "Atomic Habits is a great choice for personal growth.",
"recommend a movie": "The Pursuit of Happyness is inspiring.",
"recommend a series": "Planet Earth is an amazing documentary series.",
"recommend music": "Try listening to relaxing instrumental music.",
"what is your dream job": "Helping people is my favorite job.",
"what makes you happy": "Helping people solve problems.",
"do you like talking": "Absolutely! Conversations are my specialty.",
"can we chat": "Sure! What's on your mind?",
"i feel nervous": "Take a deep breath and believe in yourself.",
"i have an exam": "Good luck! Stay calm and do your best.",
"wish me luck": "Good luck! I believe in you.",
"pray for me": "I wish you success, peace, and happiness.",
"good job": "Thank you! I appreciate it.",
"well done": "Thanks! That means a lot.",
"awesome": "I'm glad you think so!",
"amazing": "Thank you! Happy to help.",
"cool": "Glad you liked it.",
"nice": "Thank you!",
"great": "I'm happy to hear that.",
"wow": "Pretty interesting, right?",
"really": "Yes! It's true.",
"seriously": "Absolutely!",
"what's up": "Not much! How can I help?",
"sup": "Hey! What's going on?",
"yo": "Hey there!",
"hiya": "Hello! Nice to see you.",
"long time no see": "Welcome back! It's good to see you again.",
"i'm back": "Welcome back! How can I help today?",
"did you miss me": "It's always nice to chat with you.",
"can i trust you": "I'm here to provide helpful and respectful answers.",
"do you lie": "I always try to provide accurate information.",
"are you smart": "I do my best to answer correctly.",
"who is your hero": "People who help others inspire me.",
"what makes a good person": "Kindness, honesty, and respect.",
"what is kindness": "Kindness is treating others with care and compassion.",
"what is respect": "Respect means valuing others and their feelings.",
"what is honesty": "Honesty means telling the truth.",
"why should i study": "Learning helps you grow and achieve your goals.",
"why should i work hard": "Hard work often leads to success and personal growth.",
"how do i make friends": "Be kind, listen well, and be yourself.",
"how do i stay healthy": "Eat well, exercise, sleep enough, and stay hydrated.",
"how do i sleep better": "Maintain a regular sleep schedule and avoid screens before bed.",
"how do i save money": "Spend wisely and save a little regularly.",
"how do i become confident": "Practice, prepare, and believe in yourself.",
"how do i reduce stress": "Take breaks, breathe deeply, and stay organized.",
"what is confidence": "Confidence is believing in your abilities.",
"what is patience": "Patience is staying calm while waiting.",
"what is courage": "Courage is acting despite fear.",
"what is discipline": "Discipline is doing what's needed even when it's difficult.",
"what is teamwork": "Teamwork is working together toward a common goal.",
"what is leadership": "Leadership is guiding and inspiring others.",
"what is creativity": "Creativity is thinking of new ideas.",
"what is knowledge": "Knowledge is information gained through learning and experience.",
"what is wisdom": "Wisdom is using knowledge with good judgment.",
"what is peace": "Peace is a state of calm and harmony.",
"what is respect for parents": "Respecting parents means showing love, gratitude, and kindness.",
"what is time": "Time is one of our most valuable resources.",
"why is time important": "Time once lost cannot be recovered.",
"what is success in life": "Success means achieving meaningful goals and living with purpose.",
"what is failure": "Failure is an opportunity to learn and improve.",
"can you keep me company": "Of course! I'm happy to chat with you.",
"i'm excited": "That's great! What's making you excited?",
"i'm confused": "Tell me what's confusing you, and I'll try to help.",
"i'm angry": "Take a moment to calm down before making decisions.",
"i'm scared": "It's okay to feel scared sometimes. You're stronger than you think.",
"i'm sleepy": "Maybe it's time for a short nap or a good night's sleep.",
"what is your goal": "My goal is to be helpful and informative.",
"who is your favorite person": "I enjoy helping everyone equally.",
"can you remember me": "I remember details only when memory is enabled and appropriate.",
"do you get tired": "No, I'm always ready to help.",
"thank you so much": "You're most welcome! I'm glad I could help.",

};

const defaultResponses = [
  "Sorry, I don't understand that yet.",
  "I'm not sure about that one. Could you try rephrasing?",
  "That's outside what I currently know. Try asking something else!"
];

const chatWindow = document.getElementById("chatWindow");
const messageInput = document.getElementById("messageInput");
const sendBtn = document.getElementById("sendBtn");
const typingIndicator = document.getElementById("typingIndicator");
const clearBtn = document.getElementById("clearBtn");

function getCurrentTime() {
  const now = new Date();
  let hours = now.getHours();
  const minutes = now.getMinutes().toString().padStart(2, "0");
  const ampm = hours >= 12 ? "PM" : "AM";
  hours = hours % 12;
  hours = hours === 0 ? 12 : hours;
  return `${hours}:${minutes} ${ampm}`;
}

function appendMessage(text, sender) {
  const row = document.createElement("div");
  row.classList.add("message-row", sender);

  const bubble = document.createElement("div");
  bubble.classList.add("bubble");
  bubble.textContent = text;

  const time = document.createElement("span");
  time.classList.add("timestamp");
  time.textContent = getCurrentTime();

  row.appendChild(bubble);
  row.appendChild(time);
  chatWindow.appendChild(row);

  scrollToBottom();
}

function scrollToBottom() {
  chatWindow.scrollTop = chatWindow.scrollHeight;
}

function normalize(str) {
  return str
    .toLowerCase()
    .trim()
    .replace(/[?!.,]/g, "")
    .replace(/\s+/g, " ");
}

function findResponse(userText) {
  const normalized = normalize(userText);

  if (responses[normalized]) {
    return responses[normalized];
  }

  let bestMatch = null;
  let bestMatchLength = 0;

  for (const key in responses) {
    if (normalized.includes(key) && key.length > bestMatchLength) {
      bestMatch = key;
      bestMatchLength = key.length;
    }
  }

  if (bestMatch) {
    return responses[bestMatch];
  }

  for (const key in responses) {
    if (key.includes(normalized) && normalized.length > 2) {
      return responses[key];
    }
  }

  return defaultResponses[Math.floor(Math.random() * defaultResponses.length)];
}

function showTypingIndicator() {
  typingIndicator.classList.add("active");
  scrollToBottom();
}

function hideTypingIndicator() {
  typingIndicator.classList.remove("active");
}

function handleSend() {
  const text = messageInput.value.trim();
  if (text === "") return;

  appendMessage(text, "user");
  messageInput.value = "";
  messageInput.focus();

  showTypingIndicator();

  const delay = 700 + Math.random() * 700;

  setTimeout(() => {
    hideTypingIndicator();
    const reply = findResponse(text);
    appendMessage(reply, "bot");
  }, delay);
}

sendBtn.addEventListener("click", handleSend);

messageInput.addEventListener("keydown", (e) => {
  if (e.key === "Enter") {
    handleSend();
  }
});

clearBtn.addEventListener("click", () => {
  chatWindow.innerHTML = "";
  showWelcomeMessage();
});

function showWelcomeMessage() {
  showTypingIndicator();
  setTimeout(() => {
    hideTypingIndicator();
    appendMessage("Hi! I'm FZ, your chat assistant. Ask me anything about programming, web development, technology, or just say hello!", "bot");
  }, 900);
}

window.addEventListener("DOMContentLoaded", showWelcomeMessage);